site_name: My Docs

theme : 
  name: material
  features: 
     - navigation.tabs


extra_javascript:

    - 'https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js'
    - 'https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js'
    - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'


  
# Extensions
markdown_extensions:
    - mkdocs_graphviz
     
    - pymdownx.superfences:
          custom_fences:
             - name: mermaid
               class: mermaid
               format: !!python/name:pymdownx.superfences.fence_code_format
    - attr_list
    - md_in_html
    - admonition
    - codehilite:
        guess_lang: false
    - def_list
    - footnotes
    - meta
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
nav : 
  - Home :
    - Getting Started : index.md
  - 学习笔记 :
    - 深入理解Python语言 :
      - Python的C拓展 : 学习笔记/深入理解Python语言/Python的C拓展.md
    - Cuda :
      - Gemm优化 : 学习笔记/Cuda/Gemm优化.md
      - 线程格、线程块与线程 : 学习笔记/Cuda/线程格、线程块与线程.md
      - im2col : 学习笔记/Cuda/im2col.md
    - 深度学习 :
      - BatchNormalization原理 : 学习笔记/深度学习/BatchNormalization原理.md
      - 学不明白的卷积操作 : 学习笔记/深度学习/学不明白的卷积操作.md
    - 深度学习编译器 :
      - Pytorch-Internal :
        - 一个Conv算子的生命历程 : 学习笔记/深度学习编译器/Pytorch-Internal/一个Conv算子的生命历程.md
        - Pytorch源码阅读 : 学习笔记/深度学习编译器/Pytorch-Internal/Pytorch源码阅读.md
      - 论文研读 :
        - DLcompiler综述 : 学习笔记/深度学习编译器/论文研读/DLcompiler综述.md
      - pyi文件格式 : 学习笔记/深度学习编译器/pyi文件格式.md
   
    - 编译原理 :
      - 编译器前端 :
        - First集与Follow集 : 学习笔记/编译原理/编译器前端/First集与Follow集.md
    - 深入理解计算机系统 :

      - 链接与加载 :
        - ELF文件格式 : 学习笔记/深入理解计算机系统/链接与加载/ELF文件格式.md
      - 操作系统 :
        - 虚拟化技术 :
          - 如何理解容器？ : 学习笔记/深入理解计算机系统/操作系统/虚拟化技术/如何理解容器？.md
        - MIT6.828课程 :
          - 神奇的链接 : 学习笔记/深入理解计算机系统/操作系统/MIT6.828课程/神奇的链接.md
          - lab2记录 : 学习笔记/深入理解计算机系统/操作系统/MIT6.828课程/lab2记录.md
          - 计算机是如何启动的? : 学习笔记/深入理解计算机系统/操作系统/MIT6.828课程/计算机是如何启动的?.md
        - Linux中的rootfs : 学习笔记/深入理解计算机系统/操作系统/Linux中的rootfs.md
        - linux的内存分配机制 : 学习笔记/深入理解计算机系统/操作系统/linux的内存分配机制.md
    - C++程序设计 :
      - 深入理解Cmake :
        - add_subdirectory用法 : 学习笔记/C++程序设计/深入理解Cmake/add_subdirectory用法.md
      - 头文件中的尖括号与引号 : 学习笔记/C++程序设计/头文件中的尖括号与引号.md
      - Variant的用法 : 学习笔记/C++程序设计/Variant的用法.md
    - 应用程序开发 :
      - Python程序开发 :
        - PyGame使用指南 : 学习笔记/应用程序开发/Python程序开发/PyGame使用指南.md
 
    - ACM算法 :
      - Acwing学习记录 : 学习笔记/ACM算法/Acwing学习记录.md
