site_name: My Docs

theme : 
  name: material
  features: 
     - navigation.tabs


extra_javascript:

    - 'https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js'
    - 'https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js'
    - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'


  
# Extensions
markdown_extensions:
    - mkdocs_graphviz
     
    - pymdownx.superfences:
          custom_fences:
             - name: mermaid
               class: mermaid
               format: !!python/name:pymdownx.superfences.fence_code_format
    - attr_list
    - md_in_html
    - admonition
    - codehilite:
        guess_lang: false
    - def_list
    - footnotes
    - meta
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
nav: 
  - Home:
    - Getting Started : index.md
  - 论文阅读 :
    - 机器学习系统 :
      - OSDI :
        - Roller(OSDI2022) : 论文阅读/机器学习系统/OSDI/Roller(OSDI2022).md
      - NNfusion : 论文阅读/机器学习系统/NNfusion.md
  - 学习笔记 :
    - 深入理解Python语言 :
      - Python的C拓展 : 学习笔记/深入理解Python语言/Python的C拓展.md
    - Cuda :
      - Gemm优化 : 学习笔记/Cuda/Gemm优化.md
      - 线程格、线程块与线程 : 学习笔记/Cuda/线程格、线程块与线程.md
      - 持久化线程(Persistent-Thread) : 学习笔记/Cuda/持久化线程(Persistent-Thread).md
      - im2col : 学习笔记/Cuda/im2col.md
    - 深度学习 :
      - BatchNormalization原理 : 学习笔记/深度学习/BatchNormalization原理.md
      - 学不明白的卷积操作 : 学习笔记/深度学习/学不明白的卷积操作.md
    - 深度学习编译器 :
      - Pytorch-Internal :
        - 一个Conv算子的生命历程 : 学习笔记/深度学习编译器/Pytorch-Internal/一个Conv算子的生命历程.md
        - Pytorch源码阅读 : 学习笔记/深度学习编译器/Pytorch-Internal/Pytorch源码阅读.md
      - Learning-Tvm :
        - d2l-tvm-master :
          - chapter_cpu_schedules :
            - vector_add : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_cpu_schedules/vector_add.md
            - broadcast_add : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_cpu_schedules/broadcast_add.md
            - call_overhead : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_cpu_schedules/call_overhead.md
            - packed_conv : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_cpu_schedules/packed_conv.md
            - batch_norm : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_cpu_schedules/batch_norm.md
            - pooling : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_cpu_schedules/pooling.md
            - conv : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_cpu_schedules/conv.md
            - arch : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_cpu_schedules/arch.md
            - matmul : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_cpu_schedules/matmul.md
            - block_matmul : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_cpu_schedules/block_matmul.md
            - depthwise_conv : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_cpu_schedules/depthwise_conv.md
          - chapter_getting_started :
            - from_mxnet : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_getting_started/from_mxnet.md
            - vector_add : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_getting_started/vector_add.md
            - remote : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_getting_started/remote.md
            - install : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_getting_started/install.md
          - chapter_expressions :
            - if_then_else : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_expressions/if_then_else.md
            - reductions : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_expressions/reductions.md
            - all_any : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_expressions/all_any.md
            - index_shape_expressions : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_expressions/index_shape_expressions.md
            - shapes : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_expressions/shapes.md
            - data_types : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_expressions/data_types.md
          - chapter_gpu_schedules :
            - vector_add : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_gpu_schedules/vector_add.md
            - broadcast_add : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_gpu_schedules/broadcast_add.md
            - batch_norm : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_gpu_schedules/batch_norm.md
            - pooling : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_gpu_schedules/pooling.md
            - conv : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_gpu_schedules/conv.md
            - arch : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_gpu_schedules/arch.md
            - matmul : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_gpu_schedules/matmul.md
            - depthwise_conv : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_gpu_schedules/depthwise_conv.md
          - chapter_common_operators :
            - broadcast_add : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_common_operators/broadcast_add.md
            - batch_norm : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_common_operators/batch_norm.md
            - pooling : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_common_operators/pooling.md
            - conv : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_common_operators/conv.md
            - matmul : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_common_operators/matmul.md
            - depthwise_conv : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_common_operators/depthwise_conv.md
          - chapter_references :
            - zreferences : 学习笔记/深度学习编译器/Learning-Tvm/d2l-tvm-master/chapter_references/zreferences.md
        - CPU优化 : 学习笔记/深度学习编译器/Learning-Tvm/CPU优化.md
      - pyi文件格式 : 学习笔记/深度学习编译器/pyi文件格式.md
    - 程序开发 :
      - Python程序开发 :
        - PyGame使用指南 : 学习笔记/程序开发/Python程序开发/PyGame使用指南.md
      - c语言程序开发 :
        - c语言语法 : 学习笔记/程序开发/c语言程序开发/c语言语法.md
    - 微软机器学习系统课本 :
      - 11-模型压缩与稀疏化 :
        - 11.2-基于稀疏化的模型压缩 : 学习笔记/微软机器学习系统课本/11-模型压缩与稀疏化/11.2-基于稀疏化的模型压缩.md
        - 11.1-模型压缩简介 : 学习笔记/微软机器学习系统课本/11-模型压缩与稀疏化/11.1-模型压缩简介.md
        - 11.3-模型压缩与硬件加速 : 学习笔记/微软机器学习系统课本/11-模型压缩与稀疏化/11.3-模型压缩与硬件加速.md
        - 11-前言 : 学习笔记/微软机器学习系统课本/11-模型压缩与稀疏化/11-前言.md
      - 5-深度学习框架的编译与优化 :
        - 5.1-深度神经网络编译器 : 学习笔记/微软机器学习系统课本/5-深度学习框架的编译与优化/5.1-深度神经网络编译器.md
        - 5.3-内存优化 : 学习笔记/微软机器学习系统课本/5-深度学习框架的编译与优化/5.3-内存优化.md
        - 5.4-内核优化 : 学习笔记/微软机器学习系统课本/5-深度学习框架的编译与优化/5.4-内核优化.md
        - 5.5-算子调度优化 : 学习笔记/微软机器学习系统课本/5-深度学习框架的编译与优化/5.5-算子调度优化.md
        - 5-前言 : 学习笔记/微软机器学习系统课本/5-深度学习框架的编译与优化/5-前言.md
        - 5.2-计算图优化 : 学习笔记/微软机器学习系统课本/5-深度学习框架的编译与优化/5.2-计算图优化.md
      - 6-分布式训练算法与系统 :
        - 6.2-分布式深度学习的意义 : 学习笔记/微软机器学习系统课本/6-分布式训练算法与系统/6.2-分布式深度学习的意义.md
        - 6-前言 : 学习笔记/微软机器学习系统课本/6-分布式训练算法与系统/6-前言.md
        - 6.6-分布式训练的通信协调 : 学习笔记/微软机器学习系统课本/6-分布式训练算法与系统/6.6-分布式训练的通信协调.md
        - 6.1-分布式计算简介 : 学习笔记/微软机器学习系统课本/6-分布式训练算法与系统/6.1-分布式计算简介.md
        - 6.4-深度学习并行训练同步方式 : 学习笔记/微软机器学习系统课本/6-分布式训练算法与系统/6.4-深度学习并行训练同步方式.md
        - 6.5-分布式训练系统简介 : 学习笔记/微软机器学习系统课本/6-分布式训练算法与系统/6.5-分布式训练系统简介.md
        - 6.3-分布式训练算法分类 : 学习笔记/微软机器学习系统课本/6-分布式训练算法与系统/6.3-分布式训练算法分类.md
      - 1-人工智能系统概述 :
        - 1.1-深度学习的历史，现状与发展 : 学习笔记/微软机器学习系统课本/1-人工智能系统概述/1.1-深度学习的历史，现状与发展.md
        - 1.3-深度学习系统组成与生态 : 学习笔记/微软机器学习系统课本/1-人工智能系统概述/1.3-深度学习系统组成与生态.md
        - 1.2-算法，框架，体系结构与算力的进步 : 学习笔记/微软机器学习系统课本/1-人工智能系统概述/1.2-算法，框架，体系结构与算力的进步.md
        - 1-前言 : 学习笔记/微软机器学习系统课本/1-人工智能系统概述/1-前言.md
        - 1.4-深度学习样例背后的系统问题 : 学习笔记/微软机器学习系统课本/1-人工智能系统概述/1.4-深度学习样例背后的系统问题.md
        - 1.5-影响深度学习系统设计的理论，原则与假设 : 学习笔记/微软机器学习系统课本/1-人工智能系统概述/1.5-影响深度学习系统设计的理论，原则与假设.md
      - 8-深度学习推理系统 :
        - 8.2-模型推理的离线优化 : 学习笔记/微软机器学习系统课本/8-深度学习推理系统/8.2-模型推理的离线优化.md
        - 8.4-推理系统的运行期优化 : 学习笔记/微软机器学习系统课本/8-深度学习推理系统/8.4-推理系统的运行期优化.md
        - 8.5-开发、训练与部署的全生命周期管理-MLOps : 学习笔记/微软机器学习系统课本/8-深度学习推理系统/8.5-开发、训练与部署的全生命周期管理-MLOps.md
        - 8.1-推理系统简介 : 学习笔记/微软机器学习系统课本/8-深度学习推理系统/8.1-推理系统简介.md
        - 8.3-部署 : 学习笔记/微软机器学习系统课本/8-深度学习推理系统/8.3-部署.md
        - 8-前言 : 学习笔记/微软机器学习系统课本/8-深度学习推理系统/8-前言.md
      - 9-自动化机器学习系统 :
        - 9-前言 : 学习笔记/微软机器学习系统课本/9-自动化机器学习系统/9-前言.md
        - 9.1-自动化机器学习 : 学习笔记/微软机器学习系统课本/9-自动化机器学习系统/9.1-自动化机器学习.md
        - 9.2-自动化机器学习系统与工具设计 : 学习笔记/微软机器学习系统课本/9-自动化机器学习系统/9.2-自动化机器学习系统与工具设计.md
      - 13-人工智能优化计算机系统 :
        - 13-前言 : 学习笔记/微软机器学习系统课本/13-人工智能优化计算机系统/13-前言.md
        - 13.3-落地挑战 : 学习笔记/微软机器学习系统课本/13-人工智能优化计算机系统/13.3-落地挑战.md
        - 13.1-简介与趋势 : 学习笔记/微软机器学习系统课本/13-人工智能优化计算机系统/13.1-简介与趋势.md
        - 13.2-学习增强系统的应用 : 学习笔记/微软机器学习系统课本/13-人工智能优化计算机系统/13.2-学习增强系统的应用.md
      - 7-异构计算集群调度与资源管理系统 :
        - 7.5-存储 : 学习笔记/微软机器学习系统课本/7-异构计算集群调度与资源管理系统/7.5-存储.md
        - 7.3-调度 : 学习笔记/微软机器学习系统课本/7-异构计算集群调度与资源管理系统/7.3-调度.md
        - 7.4-面向深度学习的集群管理系统 : 学习笔记/微软机器学习系统课本/7-异构计算集群调度与资源管理系统/7.4-面向深度学习的集群管理系统.md
        - 7.6-开发与运维 : 学习笔记/微软机器学习系统课本/7-异构计算集群调度与资源管理系统/7.6-开发与运维.md
        - 7.1-异构计算集群管理系统简介 : 学习笔记/微软机器学习系统课本/7-异构计算集群调度与资源管理系统/7.1-异构计算集群管理系统简介.md
        - 7-前言 : 学习笔记/微软机器学习系统课本/7-异构计算集群调度与资源管理系统/7-前言.md
        - 7.2-训练作业，镜像与容器 : 学习笔记/微软机器学习系统课本/7-异构计算集群调度与资源管理系统/7.2-训练作业，镜像与容器.md
    - 编译原理 :
      - 编译器前端 :
        - First集与Follow集 : 学习笔记/编译原理/编译器前端/First集与Follow集.md
    - 深入理解计算机系统 :
      - 链接与加载 :
        - ELF文件格式 : 学习笔记/深入理解计算机系统/链接与加载/ELF文件格式.md
      - 操作系统 :
        - 虚拟化技术 :
          - 如何理解容器？ : 学习笔记/深入理解计算机系统/操作系统/虚拟化技术/如何理解容器？.md
        - MIT6.828课程 :
          - lab4记录 : 学习笔记/深入理解计算机系统/操作系统/MIT6.828课程/lab4记录.md
          - 神奇的链接 : 学习笔记/深入理解计算机系统/操作系统/MIT6.828课程/神奇的链接.md
          - lab2记录 : 学习笔记/深入理解计算机系统/操作系统/MIT6.828课程/lab2记录.md
        - 中断与异常 : 学习笔记/深入理解计算机系统/操作系统/中断与异常.md
        - Linux中的rootfs : 学习笔记/深入理解计算机系统/操作系统/Linux中的rootfs.md
        - 页表、页表项 : 学习笔记/深入理解计算机系统/操作系统/页表、页表项.md
        - 多处理器架构 : 学习笔记/深入理解计算机系统/操作系统/多处理器架构.md
        - linux的内存分配机制 : 学习笔记/深入理解计算机系统/操作系统/linux的内存分配机制.md
        - x86体系结构 : 学习笔记/深入理解计算机系统/操作系统/x86体系结构.md
      - Gcc内联汇编 : 学习笔记/深入理解计算机系统/Gcc内联汇编.md
    - C++程序设计 :
      - 深入理解Cmake :
        - add_subdirectory用法 : 学习笔记/C++程序设计/深入理解Cmake/add_subdirectory用法.md
      - 头文件中的尖括号与引号 : 学习笔记/C++程序设计/头文件中的尖括号与引号.md
      - Variant的用法 : 学习笔记/C++程序设计/Variant的用法.md
    - ACM算法 :
      - Acwing学习记录 : 学习笔记/ACM算法/Acwing学习记录.md
  - 随想录 :
    - 万维钢 :
      - 高中是个把人分类的机器 : 随想录/万维钢/高中是个把人分类的机器.md
    - 对衡水模式的思考 : 随想录/对衡水模式的思考.md
